### ISSUE TITLE
Building problem with Visual Studio 2017

### ISSUE THREAD

**Issue by DJuego** [integeruser/FP-growth#4]
Hi again! I am working with Visual Studio 2017 (15.6.2) in Windows 10 x64.

According to the README it seems that this project has only been tested with g ++. 
But I see no reason why this project can not be **cross-platform.**

With that hope, I want to report an incident:

Simply, I am trying to run the sample main.

I had a first problem with:

```cpp
const auto minimum_support_threshold = 3;
```
I get a:
`[...]\fp-growth\src\main.cpp(80): error C2398: Element '2': conversion from 'const int' to 'uint64_t' requires a narrowing conversion`

I workaround the problem with:
```cpp
const uint64_t minimum_support_threshold = 3;
```
And the project builds successfully. ;-)

Is this the best solution?

Thanks!

DJuego

**Comment by integeruser** [comment]
Thanks for reporting! If you want, create a pull request changing the three occurrences of `auto` with `uint64_t` and I'll be glad to merge it; otherwise, I'll fix it myself in a few days.

**Comment by DJuego** [comment]
Thank you for this little fix! I have a very limited experience with git and I do not dare to make pull requests.
:-)
DJuego
